apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: micro-service-user
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
  type: NodePort

