apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: robotitus/server:latest  # Imagen correcta
        ports:
        - containerPort: 8761
      imagePullSecrets:
        - name: regcred  # Si la imagen es privada
