apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: robotitus/task-service  # Imagen correcta
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred  # Si la imagen es privada
